### ISSUE TITLE
GitHub-slack customized cheat sheet

### ISSUE THREAD

**Issue by BuddhikaD** [Satriaana/Design#14]
Here is the ticket from CB [end](Satriaana/Community-Buildup/issues/6)
DT team should have resources to proceed

**Comment by uvinduperera** [comment]
@Satriaana/design-team please consider this issue

**Comment by Thaanu2001** [comment]
Final cheat sheet PDF uploaded to [Design Repo](https://github.com/Satriaana/Design/blob/main/Slack%20Cheat%20Sheet.pdf)
